version: '3'

volumes:
    portainer_data:

services:
    portainer:
        image: portainer/portainer
        ports:
            - "9000:9000"
        restart: "always"
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
            - "./certs:/certs"
        command: 
            --ssl
            --sslcert /certs/cert.crt
            --sslkey /certs/cert.key

